### ISSUE TITLE
How to use meshmonk apart from using the DemoFaceMapping.m file

### ISSUE THREAD

**Issue by Liuywmg** [TheWebMonks/meshmonk#4]
Hi, I am very interested in using meshmonk to crop, trim, and prune 3D facial images of my own participants. I noted that the DemoFaceMapping.m file could be directly modified to run on my own facial imaging data. However, I this is just a demo file. I think there should be some more formal way for me to use meshmonk rather than using DemoFaceMapping.m file for each of my sample image.

Following the README.md file of meshmonk, I run mex_windows_all.m script to mex meshmonk functions. However, this is the end of the file regarding how to use meshmonk from Matlab on Win. My question is what should I do after mexing? Will there be an .exe file created from the mexing? I just do not want to use DemoFaceMapping.m file for my mapping, and I wish to know the orthodox way of using meshmonk, after mexing.

Thank you for sharing the great work.

**Comment by jsnyde0** [comment]
Hey, it appears we deleted some example scripts for you to learn how to use the library. We're currently looking how to best solve this (restore old examples? create new ones?). You should hear back from us within the week. If not, bump this thread again, please.

**Comment by Liuywmg** [comment]
Hi jsnyde0,

May I please know how is the preparation for the example going on? Hope the new examples could be made available to learners of meshmonk in the near future. Thank you for your effort.

**Comment by jsnyde0** [comment]
Hey @Liuywmg , someone else should be taking care of this. @alorcas can you give Liuywmg an update on this, please?

**Comment by alorcas** [comment]
Dear @Liuywmg,

You can find some examples of the mexing functions in the Demo folder.

Best,
