### ISSUE TITLE
How to get texture information using meshmonk

### ISSUE THREAD

**Issue by rabbitdsy** [TheWebMonks/meshmonk#6]
Hi, thanks for great work.

When I use meshmonk, I can get aligned pointcloud and mesh information in obj.FloatingShape, but I don't know how to find texture information.

Could you teach me how to find texture, or do I have to mannually match texture?

Thanks

**Comment by jsnyde0** [comment]
@alorcas are you processing texture with MeshMonk? It's honestly been so long ago that I'm not sure about it anymore.

**Comment by alorcas** [comment]
Hi @rabbitdsy, 

At the moment the toolbox is only focused on a shape to shape mapping and analysis, therefore texture mapping has not been included. In any case, the Template provided has a UV map which could be used to do get such texture information.
